openapi: 3.0.0
info:
  title: 'B'
  description: ''
  version: 'v1'

paths:
  /getB:
    get:
      summary: 'B'
      description: ''
      responses:
        200:
          description: 'Ok'
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './ShapeB.yml#/definitions/readonly'
                  - type: object
                    properties:
                      propB:
                        type: string
